<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../src/WinForward.Core/WinForward.Core.csproj" />
    <ProjectReference Include="../../src/WinForward.Configuration/WinForward.Configuration.csproj" />
    <ProjectReference Include="../../src/WinForward.Protocols/WinForward.Protocols.csproj" />
    <ProjectReference Include="../../src/WinForward.NdisApi/WinForward.NdisApi.csproj" />
    <ProjectReference Include="../../src/WinForward.Runtime/WinForward.Runtime.csproj" />
    <ProjectReference Include="../../src/WinForward.Windows/WinForward.Windows.csproj" />
    <ProjectReference Include="../../src/WinForward.Cli/WinForward.Cli.csproj" />
  </ItemGroup>
</Project>
