<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WinForward.Protocols</AssemblyName>
    <RootNamespace>WinForward.Protocols</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WinForward.Core/WinForward.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WinForward.Core.Tests" />
    <InternalsVisibleTo Include="WinForward.Protocols.Tests" />
    <InternalsVisibleTo Include="WinForward.Integration.Tests" />
  </ItemGroup>
</Project>
